### ISSUE TITLE
'ImportError'>: cannot import name 'InternalServerError' from 'litellm.exceptions'

### ISSUE THREAD

**Issue by mma256** [OpenDevin/OpenDevin#3127]
Hello, 

I am trying to run the swebench lite evaluation. I followed all the steps listed in the [opendevin](https://github.com/OpenDevin/OpenDevin) and [evaluation readme](https://github.com/OpenDevin/OpenDevin/tree/main/evaluation/swe_bench). 

Everything was working with CodeAct version 1.5. However, when I moved to version 1.8 and try to evaluate CodeAct agent using 
```
./evaluation/swe_bench/scripts/run_infer.sh azure-gpt-4o HEAD CodeActAgent 8 30
``` 
I faced the following error: 
```
The given hash is equivalent to the current HEAD
Build sandbox locally
[+] Building 0.1s (19/19) FINISHED                                                                            docker:default
 => [internal] load .dockerignore                                                                                       0.0s
 => => transferring context: 2B                                                                                         0.0s
 => [internal] load build definition from Dockerfile                                                                    0.0s
 => => transferring dockerfile: 1.50kB                                                                                  0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                         0.1s
 => [ 1/15] FROM docker.io/library/ubuntu:22.04@sha256:340d9b015b194dc6e2a13938944e0d016e57b9679963fdeb9ce021daac43022  0.0s
 => CACHED [ 2/15] RUN apt-get update && apt-get install -y     curl     wget     git     vim     nano     unzip     z  0.0s
 => CACHED [ 3/15] RUN mkdir -p -m0755 /var/run/sshd                                                                    0.0s
 => CACHED [ 4/15] RUN ln -s /usr/bin/python3 /usr/bin/python                                                           0.0s
 => CACHED [ 5/15] RUN mkdir -p /opendevin && mkdir -p /opendevin/logs && chmod 777 /opendevin/logs                     0.0s
 => CACHED [ 6/15] RUN wget --progress=bar:force -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/l  0.0s
 => CACHED [ 7/15] RUN bash Miniforge3.sh -b -p /opendevin/miniforge3                                                   0.0s
 => CACHED [ 8/15] RUN chmod -R g+w /opendevin/miniforge3                                                               0.0s
 => CACHED [ 9/15] RUN bash -c ". /opendevin/miniforge3/etc/profile.d/conda.sh && conda config --set changeps1 False &  0.0s
 => CACHED [10/15] RUN echo "" > /opendevin/bash.bashrc                                                                 0.0s
 => CACHED [11/15] RUN rm -f Miniforge3.sh                                                                              0.0s
 => CACHED [12/15] RUN /opendevin/miniforge3/bin/pip install --upgrade pip                                              0.0s
 => CACHED [13/15] RUN /opendevin/miniforge3/bin/pip install jupyterlab notebook jupyter_kernel_gateway flake8          0.0s
 => CACHED [14/15] RUN /opendevin/miniforge3/bin/pip install python-docx PyPDF2 python-pptx pylatexenc openai           0.0s
 => CACHED [15/15] RUN /opendevin/miniforge3/bin/pip install python-dotenv toml termcolor pydantic python-docx pyyaml   0.0s
 => exporting to image                                                                                                  0.0s
 => => exporting layers                                                                                                 0.0s
 => => writing image sha256:3a69b60594c1d384fe91a8568f80c61384480dff35787fa2318ed73b69d4a09d                            0.0s
 => => naming to docker.io/library/eval-sandbox                                                                         0.0s
USE_INSTANCE_IMAGE not specified, use default false
USE_INSTANCE_IMAGE: false
ERROR:root:  File "<string>", line 1, in <module>
  File "/home/azureuser/localfiles/OpenDevin/agenthub/__init__.py", line 3, in <module>
    from opendevin.controller.agent import Agent
  File "/home/azureuser/localfiles/OpenDevin/opendevin/controller/__init__.py", line 1, in <module>
    from .agent_controller import AgentController
  File "/home/azureuser/localfiles/OpenDevin/opendevin/controller/agent_controller.py", line 5, in <module>
    from opendevin.controller.agent import Agent
  File "/home/azureuser/localfiles/OpenDevin/opendevin/controller/agent.py", line 11, in <module>
    from opendevin.llm.llm import LLM
  File "/home/azureuser/localfiles/OpenDevin/opendevin/llm/llm.py", line 12, in <module>
    from litellm.exceptions import (

ERROR:root:<class 'ImportError'>: cannot import name 'InternalServerError' from 'litellm.exceptions' (/home/azureuser/.cache/pypoetry/virtualenvs/opendevin-kxseWP-G-py3.11/lib/python3.11/site-packages/litellm/exceptions.py)
```

I am using GPT-4o for evaluation. 
```
[azure-gpt-4o]
model="azure/gpt-4o"
```

Please let me know how to fix this.

**Comment by xingyaoww** [comment]
Are you using the latest commit from the `main` branch?

**Comment by xingyaoww** [comment]
Did you run `make build` before start running the eval? This might be caused by out-dated `litellm` package

**Comment by mma256** [comment]
@xingyaoww 
yes, I am using the latest commit from the main branch. I didn't run the make build after moving to version 1.8. Let me try that first.

**Comment by mma256** [comment]
The issue is fixed after running the ```make build```. Thank you.
